import React from "react";
import Navbar from "../../components/Navbar";
import Navbar2 from "../../components/Navbar2/index";

const Bisnis = () => {
  return (
    <>
      {/* <Navbar /> */}
      <Navbar2 />
      <div className="h-[200vh] bg-sky-100">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas quasi deleniti molestias? Tempora cum assumenda, possimus deserunt doloribus veritatis necessitatibus officiis doloremque. Perferendis illo sequi, explicabo ex amet
          quis debitis quos, magni illum quibusdam deserunt laudantium repellat minus. Temporibus veniam provident perferendis architecto nesciunt amet assumenda ut. Libero ipsa ab exercitationem nemo voluptatem temporibus autem tempora
          labore soluta, porro aut esse, reiciendis officiis asperiores explicabo sunt ad sapiente ipsum aspernatur, repudiandae deserunt. Quibusdam dolore cupiditate aliquid, tenetur autem impedit quisquam est aut quae earum aperiam non
          inventore rem sequi ut? Voluptatem quas culpa sunt debitis ea magni blanditiis, laboriosam accusamus et molestias dolorum ipsa eveniet nostrum numquam ut modi ex suscipit corporis temporibus? Suscipit deleniti rem velit odit
          officia praesentium perferendis, corrupti fugiat maiores nulla expedita ex, voluptatum voluptates! Iusto laboriosam sapiente, nulla similique, distinctio rem, amet officiis dolore optio sint maxime. Sint, nostrum! Ipsa,
          perspiciatis quaerat inventore ullam esse non sit dolor molestias quasi amet. Assumenda sed inventore laborum temporibus dolorem nulla enim non molestiae. Laborum, illum. Veniam, sequi? Magni laborum, rem quidem aut accusamus
          repellat aliquam, voluptas maxime quis qui nesciunt odio, ut eum? Perferendis veritatis itaque iure hic incidunt provident commodi illo. At asperiores veniam, labore id ut quam exercitationem quidem numquam voluptate provident sit
          similique nam libero consequatur beatae dignissimos! Autem quam quisquam placeat, praesentium provident rerum facilis perspiciatis perferendis corrupti eligendi distinctio quaerat necessitatibus excepturi, suscipit dolores neque
          eveniet sed voluptatibus corporis natus dolorem, error hic. Delectus cupiditate repudiandae, cumque, quasi corporis voluptates reiciendis quam quisquam ullam iure quis saepe magnam quia libero nobis vitae! Fuga quisquam ab dolor
          unde quas beatae voluptates. Cupiditate delectus repudiandae unde libero dignissimos sint! Fugiat ipsam rerum facere aspernatur saepe ullam, nihil iste, excepturi labore quod aliquam quaerat nisi voluptas asperiores voluptates
          enim cum suscipit praesentium alias natus quo. Labore distinctio magni tempore molestiae hic beatae cupiditate soluta optio. Cumque beatae consequatur iure magnam, rerum earum voluptatem similique assumenda dolorem provident
          minima est! Maxime fuga repellat officiis totam quasi iusto molestiae corporis excepturi sint possimus esse laborum nulla porro tempora numquam magni vel placeat nam, in nemo tempore nobis! Itaque voluptatem eligendi ex, neque
          nisi exercitationem aperiam repellat facilis id, mollitia reprehenderit dolorem et, officia fugiat nostrum maxime consectetur! Quia, sequi quaerat accusamus ut voluptatibus ab quam suscipit excepturi commodi perferendis harum.
          Reprehenderit, omnis commodi autem, quibusdam odio saepe id temporibus possimus hic, sunt aliquid quam optio sapiente dolor quisquam ullam non rem eaque! Minus similique nemo dolor velit impedit culpa vel, nulla a error? Officia
          ut dolores rem rerum aut accusamus dolor veniam saepe tenetur eum laborum totam maiores porro eligendi illo deleniti, consectetur enim neque. Minus sapiente possimus odit illo perspiciatis ipsam. Corporis, doloribus cumque nostrum
          tempore iure dolore molestias, voluptas porro ipsum quaerat temporibus laboriosam non accusamus laborum quod? Molestiae voluptatum nulla non ullam dolores expedita ex necessitatibus possimus quia quos. Eligendi libero, itaque qui
          unde magnam mollitia repudiandae dicta? Delectus quos incidunt possimus excepturi, cumque temporibus itaque facilis laudantium corporis natus cum aliquid rerum fugiat perferendis debitis, veritatis nulla labore numquam culpa quas
          iusto rem quis sunt. Asperiores a in repellat sint et exercitationem inventore mollitia accusamus officia tempora expedita odio maxime, recusandae consequuntur, vero eum dolor non eveniet. Qui dolor illum cumque sed recusandae
          omnis sit saepe non. Eaque voluptas repellat laborum distinctio vero quidem? Maxime numquam, non, aut distinctio eos incidunt repudiandae porro quod illum omnis accusamus consequuntur, atque ipsum harum. Hic cumque dolor similique
          dignissimos facere, aliquam architecto tempore aspernatur doloremque suscipit ut non magnam quasi accusantium earum, possimus natus eveniet quas sequi velit ratione provident? Aspernatur ipsum excepturi doloremque molestias, ea et
          veritatis sit, consequatur quos magnam numquam distinctio corporis delectus tenetur laborum beatae natus sunt officiis aut optio alias dolor tempore minima ex. Libero reiciendis sed aperiam dolor eveniet? Corporis earum ipsum in
          enim nihil vero cupiditate. Eveniet numquam dignissimos error officiis deleniti? Quos odit temporibus cupiditate, molestias quasi nostrum id commodi earum tempore modi impedit eius dolores atque velit. Ab consectetur incidunt
          excepturi id, non nulla voluptatum iure veniam fugiat officia quia rem asperiores perferendis dicta quis veritatis quaerat at dolorem? Neque tenetur vitae quo iste vero, at aspernatur, asperiores necessitatibus mollitia quasi
          delectus maxime tempora voluptas? Sed tempore rerum odit hic eius, vel quidem excepturi labore esse perspiciatis eum et autem voluptates quia ullam delectus! Tempore inventore commodi veritatis! Eos, perspiciatis! Sed ex quas ab
          iure placeat dicta tempore totam corrupti suscipit laboriosam illo, vitae in harum, magnam error et, possimus optio consequuntur unde. Ullam atque consequuntur doloribus sequi ipsam blanditiis esse harum nostrum. Tenetur alias
          sunt eligendi dolore? Dicta quae facere quis fugit cum, eveniet harum neque ea mollitia facilis esse nesciunt temporibus sint culpa dolor soluta deleniti deserunt ab quos debitis! Mollitia soluta cumque reiciendis quam cum maxime
          molestias quasi porro animi culpa pariatur eveniet accusamus voluptates quas dolores obcaecati nam officiis sunt excepturi, deserunt tempore atque. Doloribus, ducimus earum. Aspernatur quis odio accusantium. Exercitationem quos
          amet tempore. Repudiandae deleniti dolore excepturi, temporibus non aperiam itaque doloribus, nesciunt tempore laudantium repellat vel in. Cum laudantium, delectus amet consectetur minima nisi vitae nobis. Perferendis blanditiis
          maxime pariatur temporibus ullam repellendus vero sapiente veniam unde quis, vitae rem. Obcaecati dolorum labore amet repudiandae accusamus ab ex quidem. Quidem, culpa, magni, pariatur unde molestiae quos sequi quis ut harum at
          esse? Laudantium sit facere, itaque accusantium maiores doloremque repellendus, magnam dolorum totam culpa deserunt. Iste, assumenda suscipit? Molestias necessitatibus porro exercitationem sint distinctio iure at officiis illum
          ex. Qui aperiam rerum earum sequi officiis excepturi ratione, magni voluptate ipsum, eligendi suscipit? Eligendi impedit harum corporis nam laboriosam, maxime dicta dolores illo quos animi fugit quisquam, labore magni adipisci,
          exercitationem nesciunt recusandae? Adipisci incidunt eius harum explicabo iusto sint nemo possimus tempore accusantium vel ullam eaque consequatur, fugiat consectetur praesentium mollitia, cumque a nulla sequi consequuntur alias
          asperiores deleniti. Rem explicabo quos dolore reiciendis voluptates tenetur ratione ad dolorum eum quam harum, provident itaque, ipsam quidem sed facilis, hic velit corporis incidunt quaerat. Sint, dolorem? Provident sint ut
          reprehenderit eaque voluptate quod inventore doloremque ad ea optio. Minima fugit id consequuntur. Neque harum nam aspernatur corporis delectus consequuntur assumenda suscipit, eius doloribus nemo deleniti voluptatum architecto
          quia quis id nobis fuga excepturi expedita unde error quidem? Molestias delectus doloremque, maxime accusamus saepe voluptatem, repellendus quae, odit sequi possimus ea! Facere est maiores aut, veritatis magni doloribus
          accusantium necessitatibus quae nihil sed aspernatur, sequi aperiam voluptate ab libero cum nostrum laudantium? Tenetur vitae quia magnam, alias eum in neque voluptas tempore dignissimos aperiam atque temporibus necessitatibus
          maxime voluptatibus nemo earum. Recusandae voluptate voluptatem optio, sed nesciunt, consectetur delectus quasi natus asperiores eveniet consequuntur nemo accusantium deserunt eius ut placeat necessitatibus? Ut harum facilis
          voluptate sunt minima possimus. Porro incidunt impedit corrupti tempora cum temporibus, dignissimos quidem minima dolorum eveniet doloribus eaque ducimus? Ab perspiciatis vel nihil, labore amet quos. Sint optio fugiat eveniet
          aspernatur atque, minima quam, veniam placeat eum praesentium cumque repudiandae accusantium iusto facilis! Et ducimus voluptatum, dolores labore, ratione, corrupti sint repudiandae est aut quaerat repellat. Tenetur harum, ut
          tempora amet quidem quibusdam alias illo sequi qui deserunt laboriosam, rem deleniti officiis. Officia mollitia quasi voluptatum animi laborum adipisci beatae dolores vero! Laborum dicta laudantium atque, incidunt eligendi
          voluptas praesentium earum reprehenderit dolorem eaque inventore nisi nulla quas. Eius adipisci tempora dolorem, aliquid provident et praesentium sequi nobis perspiciatis ut dicta eos asperiores, doloribus eaque laudantium? Ipsam
          officia laudantium alias perspiciatis cum delectus dicta architecto? Aliquam, asperiores? Maxime ratione odio ea ullam, ad rerum earum quasi blanditiis ab necessitatibus accusantium nisi tempore possimus expedita cupiditate minus
          culpa, architecto ut fugit magni accusamus, fugiat quia optio? Perspiciatis eligendi alias debitis sequi illo ab dolorem voluptate magnam unde asperiores non enim ad nisi, cumque nihil fugit laborum voluptatem, error cupiditate
          odio natus quis nulla? Numquam ut non eligendi nihil quas, nesciunt sunt consequuntur, autem assumenda nisi laboriosam illum sed quis modi, praesentium animi! Necessitatibus excepturi, sunt iure itaque voluptate sed a odio facilis
          similique eligendi labore, consequuntur, rem eum sint accusantium aut distinctio rerum totam quod deserunt? Tempora reiciendis architecto veritatis, similique sunt repellendus asperiores libero commodi aliquid atque maiores
          corrupti qui sapiente alias porro, placeat tempore cum reprehenderit provident dolores assumenda incidunt saepe minima quasi! Placeat tempora cum nisi quidem error exercitationem saepe ducimus aspernatur. Soluta dignissimos non
          voluptatibus ipsum necessitatibus quo, sunt accusamus obcaecati veniam beatae facere porro ipsa corporis, eius, repellendus laborum quos. Eaque odio quisquam vitae in eius laboriosam et obcaecati aliquam exercitationem facilis
          esse commodi accusantium deserunt quos, corporis quia libero cum quam tempore eos atque blanditiis natus. Cum consectetur dolor iusto quod culpa accusamus illo molestias magni, est labore pariatur optio maiores debitis itaque
          quidem officiis sequi rem similique facilis hic repudiandae voluptatibus. A veniam, non, beatae mollitia voluptatem odit ea fugiat praesentium magnam quibusdam aperiam recusandae molestiae? Fugiat sint quos nostrum doloribus
          animi, veritatis blanditiis sequi neque ducimus quidem culpa beatae, aut eos. Sapiente corporis, commodi fugiat ex velit officiis non cupiditate molestiae laboriosam? Rerum, iste possimus praesentium culpa consectetur beatae!
          Delectus consectetur rerum sunt. Vel dignissimos optio corporis quod pariatur atque, similique est dolorem deleniti commodi blanditiis voluptas reprehenderit repellendus. Eligendi, asperiores non consequatur a fuga soluta
          assumenda nesciunt cum, ratione placeat, error harum. Quaerat laboriosam distinctio laudantium? Natus dicta voluptatum possimus placeat exercitationem quae quisquam necessitatibus? Praesentium consectetur nulla iste et accusantium
          quis, officia magnam, aliquid amet quam iusto dignissimos, ratione consequuntur delectus ut quibusdam voluptatem aperiam minus odio? Distinctio reiciendis dignissimos placeat consequatur tempora quasi, quisquam aliquid facilis at
          a laudantium, omnis rem quod cumque aut odio ducimus possimus. Quidem quia, cumque enim aperiam esse repudiandae praesentium incidunt vitae, possimus, unde mollitia in voluptatem illum dolores. Eveniet fugit amet impedit at
          obcaecati natus praesentium iure. Perspiciatis eveniet suscipit dolor nesciunt repudiandae quidem ratione, eum esse, ex nulla architecto vero mollitia id eos! Maiores id error iste accusantium officia earum provident sit
          voluptate, cum necessitatibus deleniti, quasi laudantium et voluptates illo saepe officiis corporis laboriosam. Officia ad ipsum nihil optio, quidem pariatur quod nam magni doloremque voluptate eius. Omnis, quod nisi? Odio error,
          consectetur facere earum laudantium dolore dignissimos accusantium quae atque optio inventore, ipsum necessitatibus quos asperiores expedita, non provident sunt tenetur libero ratione quaerat corporis aut molestiae! Incidunt sunt
          fugiat adipisci architecto consequatur quis possimus velit, similique deleniti rerum aut voluptas asperiores praesentium explicabo eos harum quae consectetur exercitationem perferendis hic perspiciatis eligendi esse? Consequatur
          veritatis aperiam molestiae labore provident recusandae quaerat iure sed, quam explicabo dolore eaque sapiente perspiciatis reiciendis ad, ipsum tenetur facilis voluptatibus neque obcaecati? Molestiae officia unde odio. Ea
          voluptas, voluptatem amet molestias ut beatae assumenda, eos non harum eveniet quibusdam, est reiciendis quaerat dolor architecto tenetur! Corrupti libero cumque mollitia odio. Nemo, quam animi. Placeat nulla mollitia soluta
          quibusdam qui nihil accusantium corrupti quas natus fugiat laboriosam necessitatibus, vel pariatur commodi, veniam explicabo obcaecati facilis ratione magnam fugit voluptates iure perferendis. Exercitationem quo minus harum in,
          ipsa quidem animi ea architecto. Blanditiis, quae reprehenderit ex delectus velit fuga vitae debitis, dolore tempore nihil impedit voluptas tenetur laborum? Natus tempora quibusdam similique officiis id tenetur consectetur,
          nostrum expedita laborum? Quis, voluptatum modi veritatis quibusdam rerum consequatur eum corrupti cumque, impedit ab rem exercitationem illo dolore nisi quaerat quasi natus sequi nemo esse neque alias maxime numquam. Quasi
          sapiente obcaecati illo ducimus iure dolorem nulla molestias, sequi eligendi. A ab consectetur magnam, totam placeat iusto voluptas molestias rerum minima hic repellat nemo neque necessitatibus, et impedit natus ea optio quam
          tempora quisquam commodi. Esse veritatis est quam perspiciatis iste unde quos facere, impedit tenetur nulla deserunt beatae quod corrupti ipsa, accusamus eveniet, ut fuga eum consectetur. Iste, blanditiis. Ex facere officiis quas
          animi beatae nihil nemo, obcaecati repudiandae sunt praesentium, omnis assumenda quibusdam illo. Accusamus, adipisci? Temporibus voluptatum ut cum placeat impedit. Labore, quasi. Velit ratione doloribus aliquid quas? Debitis
          cupiditate illum vero nulla eos delectus animi molestias ratione quae ex sequi aperiam repellat nisi officia laudantium eum quis aspernatur, dignissimos maiores deleniti aliquam. Iste neque optio fugit distinctio? Fuga incidunt
          fugiat saepe reprehenderit eligendi ex dolorum nemo, facilis explicabo pariatur neque harum similique quis soluta! Nisi rerum magnam ad beatae neque exercitationem doloremque commodi inventore amet velit soluta et culpa, quasi
          eaque molestias libero, officia, itaque ex eligendi incidunt est porro tenetur? Quis, quod incidunt officiis provident repellat veritatis! Fugiat, voluptatem alias ipsa perferendis ipsam in! Non consequuntur animi blanditiis fuga
          ut voluptatem libero odit delectus beatae! Iure, suscipit quis. Iusto placeat suscipit recusandae. Facilis est delectus, aliquam iusto omnis quaerat consequatur illum molestias? Nisi temporibus odit eveniet ipsum a odio deleniti
          quia ratione, minima nam repellat error optio repudiandae amet, soluta pariatur quaerat voluptatem doloremque accusamus culpa possimus doloribus. Recusandae, libero ratione laudantium necessitatibus tempora est quos quis unde hic
          magnam dolore ipsum eius in adipisci sed omnis rem expedita facilis voluptate molestias quo. Tempora enim quas, voluptatum obcaecati vero et porro suscipit. Nihil eligendi laboriosam perferendis quos magni omnis quia dignissimos
          harum quasi exercitationem, in quisquam, labore commodi amet aliquid ab ea voluptates expedita ratione culpa non temporibus. Quas quos error, et eaque atque recusandae minima sint illum rem doloribus temporibus ea deleniti
          officiis veniam quaerat explicabo doloremque, soluta libero obcaecati sequi, autem necessitatibus vel consequuntur! Neque mollitia odio est numquam quod, veritatis consequatur repellat, aut deleniti vel repellendus sunt, aliquid
          temporibus dolore! Magnam ab cum incidunt, consequuntur iusto, ipsa blanditiis nulla architecto sint porro reiciendis. Error voluptates id distinctio veritatis aut similique deserunt illum iure consequatur quo placeat
          reprehenderit excepturi molestiae sapiente, commodi quas voluptatem mollitia eos architecto fugiat soluta ducimus, doloremque, quia nostrum. Fugit corporis ea esse earum asperiores, molestias explicabo, pariatur, recusandae
          similique illo eligendi cumque nemo harum facere numquam non totam perferendis. Enim tempora aut unde aperiam minima hic reiciendis qui in veniam vitae? Iure velit est placeat distinctio tempore, cumque repellendus corrupti quis
          eveniet explicabo quisquam vel! Veritatis quasi, aperiam ipsum cum tenetur enim repellendus dignissimos molestias sunt sed voluptates. Magnam eius nesciunt nemo, tempora incidunt quo deserunt. Corrupti deleniti natus
          reprehenderit. Deleniti ipsam reprehenderit magnam quo inventore dignissimos facilis corporis mollitia, itaque earum explicabo ducimus ea culpa reiciendis id perferendis voluptatum voluptatem enim atque voluptates hic praesentium
          consequatur quaerat maxime. Provident ab, tempora quod explicabo tempore repudiandae consectetur numquam ea velit deleniti cumque ducimus quaerat nisi nulla rem similique! Expedita optio excepturi corrupti facere magnam iusto
          repudiandae impedit est enim esse laudantium itaque quisquam, nemo sed at amet labore ad adipisci quam officia praesentium ex temporibus nam. Dolores vero temporibus nemo molestiae numquam blanditiis quasi, beatae impedit suscipit
          excepturi officia est labore magnam. Voluptatem ut, saepe id aperiam sequi blanditiis repudiandae soluta et dignissimos hic voluptatum exercitationem voluptate vitae deserunt quos enim perferendis quaerat temporibus dolorum quo
          dolor provident. Obcaecati sit adipisci in quas rem veniam modi fugit doloribus eligendi optio fugiat harum iure, impedit dicta eaque nesciunt voluptas illum voluptatem ex, molestiae itaque recusandae exercitationem. Eum laborum
          quaerat quidem nihil id, quibusdam quasi. Et saepe laboriosam ipsam impedit, eligendi in qui soluta labore nobis mollitia a ad ratione ea doloribus eos odio maiores nesciunt? Id nulla odit magni corrupti maxime! Nobis delectus
          animi a, iure inventore, qui dolore deserunt eaque, cum consectetur iusto est magni similique distinctio nihil error? Dolor ipsum quibusdam eaque et minima placeat vel alias, odit distinctio tempore mollitia eos inventore itaque
          minus! Corrupti assumenda, repellat nam iusto dicta sapiente magnam ullam quisquam autem dignissimos aut illo et odio voluptatum veritatis ex fugiat a consequatur ut possimus sequi natus iure recusandae. Nisi, quis cum. Deleniti,
          harum impedit id delectus aliquam provident facere? Assumenda aut natus obcaecati? Rem libero iusto autem officia suscipit, necessitatibus ratione id eum nihil voluptatibus cupiditate voluptatum excepturi rerum consequuntur hic
          laudantium eius dolores repellendus obcaecati? Deserunt iure sed similique quod deleniti cupiditate eaque, laudantium expedita quisquam itaque ullam neque. Quasi earum molestiae id voluptatem architecto iste! Doloremque dicta
          tenetur numquam consequuntur accusantium nemo amet, optio delectus obcaecati aut? Ipsa ipsam ad delectus repellat hic eos odio obcaecati quae nemo iure architecto ea voluptatem incidunt explicabo, error consequuntur debitis
          assumenda illum cum cupiditate quo autem! Commodi velit eligendi quia voluptatum corporis incidunt esse numquam at laudantium. Omnis dolorem possimus cum non voluptatum dicta sed, fugiat voluptatem enim, distinctio incidunt
          numquam pariatur consequuntur ipsam reprehenderit totam quos inventore delectus perferendis illum saepe? Nostrum aspernatur quo consequatur facilis sed ipsam eligendi voluptatum? Beatae, velit! Numquam esse voluptates cupiditate
          ratione, tempore quod quidem natus, ut molestias, sit a optio eius dolorem commodi minus dicta reprehenderit magni fugit? Ducimus voluptate qui reprehenderit et molestiae, explicabo ab sequi vitae id? Labore, quod quasi at
          accusantium ducimus voluptates voluptatem dolores odio, itaque expedita praesentium harum ullam eligendi fuga beatae voluptatum blanditiis necessitatibus neque in aut? Porro quos repudiandae laboriosam unde perspiciatis?
          Repellendus totam in quidem commodi. Praesentium in iure, commodi neque illum cupiditate deleniti! Consequatur rerum expedita laudantium est, vitae velit id porro tempora modi error, fugit mollitia alias! Et non soluta, sunt
          doloremque quis consequuntur maiores totam dolorem iste nostrum vitae, voluptatibus labore reiciendis nobis ullam similique magnam aliquid aliquam eos iusto? Placeat cupiditate dolorem cumque alias exercitationem. Veniam,
          doloribus quo accusamus eius at necessitatibus harum, nemo voluptates distinctio voluptatem velit praesentium recusandae suscipit soluta nihil porro, aliquid dicta eveniet possimus? Tenetur tempora nobis cum eius quod fugit quasi
          voluptas quo dolore sapiente necessitatibus, sunt delectus qui alias laborum dolor unde rem voluptate est repellat officiis, ipsum sed! Molestiae nostrum inventore perspiciatis voluptate ipsum nihil, mollitia quisquam nisi omnis
          sunt esse nemo harum neque tenetur earum quod culpa officiis, dolores obcaecati ipsam accusantium eos cum. Dolore assumenda nesciunt voluptatum ea reiciendis dolor distinctio blanditiis architecto, autem asperiores hic fuga
          nostrum, earum repellendus in error libero labore suscipit? Molestias porro atque earum quod quos ipsam quo saepe maiores sapiente! Minima ad aliquam repellat officiis, ex illo inventore libero qui dolorum nostrum, cupiditate
          dolores recusandae? Magni, architecto? Ab consequatur quo deserunt accusantium mollitia odio voluptate quidem illo laborum quia praesentium sunt vel, consectetur obcaecati eos natus nemo deleniti! Unde dolore repellendus illum
          libero cupiditate minus quisquam est facilis? Ipsam quidem nihil ut nam aliquid pariatur, fuga qui!
        </p>
      </div>
    </>
  );
};

export default Bisnis;
